version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: studyabroad
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
  api:
    build: ./apps/api
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/studyabroad
    depends_on:
      - db
    ports:
      - '4000:4000'
  web:
    build: ./apps/web
    depends_on:
      - api
    ports:
      - '3000:3000'
